export const GOOGLE_MAPS_API_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ??
  process.env.GOOGLE_MAPS_API_KEY ??
  "AIzaSyB5NCPpj4QeNbyie8ZIPa5aA6cS4mcYLEk";

export const GOOGLE_CALENDAR_CLIENT_ID =
  process.env.GOOGLE_CALENDAR_CLIENT_ID ?? "{{GOOGLE_CALENDAR_CLIENT_ID}}";

export const GOOGLE_CALENDAR_CLIENT_SECRET =
  process.env.GOOGLE_CALENDAR_CLIENT_SECRET ?? "{{GOOGLE_CALENDAR_CLIENT_SECRET}}";

export const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "{{SUPABASE_URL}}";

export const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
  process.env.SUPABASE_ANON_KEY ??
  "{{SUPABASE_ANON_KEY}}";
